### add a User to dB
POST http://localhost:3000/Kurse HTTP/1.1
Content-Type: application/json

{
  "cursname": "Web development",
  "content": "Web-Kram",
  "classNumber": "001",
  "trainer":"Jerry",
  "location": "Hamburg"
}

### Delete by ClassNumber
DELETE http://localhost:3000/Kurse/001 HTTP/1.1