### View All
GET http://localhost:3000/Kurse HTTP/1.1

### add a User to dB
POST http://localhost:3000/Kurse HTTP/1.1
Content-Type: application/json

{
  "cursname": "Nähen für linkshänder",
  "content": "Kleidung nähen",
  "classNumber": "001",
  "trainer":"Elka",
  "location": "Timmendorf"
}
### einfügen Admin
POST http://localhost:3000/Kurse/001 HTTP/1.1
Content-Type: application/json

{
  "name": "Peter Lustig",
  "username": "Admin",
  "password": "123",
  "Infomation":"Löschen von Kursen nicht erlaubt"
}

### Update content
PATCH http://localhost:3000/Kurse/update HTTP/1.1
Content-Type: application/json

{"oldContent" : "Kleidung nähen",
 "newContent" : "Nähen toller Sachn die keiner braucht"}

### Informationen hinzufügen
PATCH http://localhost:3000/addInfo/admin HTTP/1.1
Content-Type: application/json

{
  "information": "this admin may delete Courses"
}


### Delete by ClassNumber
DELETE http://localhost:3000/Kurse/005 HTTP/1.1

### login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin", 
"password": "admin"
}
